---
name: Build

on: [ push, pull_request ]

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build tools
        run: git clone https://git.anotherfoxguy.com/AnotherFoxGuy/build-tools.git %BUILD_TOOLS_PATH%
        shell: cmd

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Configure
        run: |
          cmake -G"NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release .
        shell: cmd

      - name: Build
        run: jom
        shell: cmd